export const SET_LOADING = '@SET_LOADING';

// Dashboard
export const GET_POKEMON_SUCCESS = '@GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAILURE = '@GET_POKEMON_FAILURE';
export const GET_POKEMON_LOADING = '@GET_POKEMON_LOADING';

// Detail
export const GET_POKEMON_DETAIL_SUCCESS = '@GET_POKEMON_DETAIL_SUCCESS';
export const GET_POKEMON_DETAIL_FAILURE = '@GET_POKEMON_DETAIL_FAILURE';
export const GET_POKEMON_DETAIL_LOADING = '@GET_POKEMON_DETAIL_LOADING';
export const GET_DISABLE_CATCH = '@GET_DISABLE_CATCH';
