name: react-native-android-build-apk
on:
  push:
    branches:
      - main
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && chmod +x ./gradlew && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: 006Axel/MyPokemon
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: staging
          file: android/app/build/outputs/apk/release/app-release.apk
          notifyTesters: true
          debug: false